
server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    #   url: jdbc:mysql://localhost:3306/anime?useSSL=false&createDatabaseIfNotExist=true
    url: jdbc:mysql://localhost:3306/anime?createDatabaseIfNotExist=true # pode ser usado assim tambem
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update  #toda vez que a aplicação for iniciada o banco de dados vai ser atualizado
    show-sql: true

