
server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    #   url: jdbc:mysql://localhost:3306/anime?useSSL=false&createDatabaseIfNotExist=true
    url: jdbc:mysql://localhost:3306/anime?createDatabaseIfNotExist=true # pode ser usado assim tambem
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update  #toda vez que a aplicação for iniciada o banco de dados vai ser atualizado

# faz o log do sql fazer parte do logback do log padrão do spring, deixa mais orgazizado e a performace é melhorada, em relação ao show-sql:true do jpa, que só printava no console
# aqui esta se especificando o log do SQL do pacote hibernate
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

